id: D68098764
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:00:30+00:00'
last_modified: '2022-05-26T08:15:22.452565+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    2dee:
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      order: 14
      base_file: 2dee.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
